// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlggxwluvnmcmelyvgrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZ2d4d2x1dm5tY21lbHl2Z3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTI2MjgsImV4cCI6MjA2OTAyODYyOH0.pulPTLEv3sXR6Ro9-y1cv_vLpk9qarVQEdY4CKjC3nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});